#!/bin/sh
# Deploy the latest version of the web app to GitHub Pages on git push.
#
# This is stored in a non-standard location, so to tell git to
# use the hooks in this directory, make sure to run, from the 
# project root directory:
# git config core.hooksPath .githooks

npm run deploy
